### ISSUE TITLE
Bug in HazardCurveLocal

### ISSUE THREAD

**Issue by lstrahm** [opensha/opensha-apps#10]
Steps to reproduce: (PLEASE FILL IN)

Other info: I have a couple of new machines; a MacBookPro and a Dell Inspiron.  I get the following error on both when I attempt to run the Hazard Curve and Hazard Spectrum using UCERF3 Single Branch:  "An error occured when instantiating UCERF3 Single Branch ERF"  That appears to be the only ERF giving me trouble.

It will be removed from the list. If you wish, you can submit a bug report by clicking below. To receive updates on the bug report, it is important that you leave your e-mail address in the 'reporter' field.

Application: HazardCurveLocal
Version: 1.5.2
Bulid Type: Production
Java Version: 1.8.0_271 (Oracle Corporation)
Operating System: Windows 10 (arch: amd64, version: 10.0)
JVM Memory (MB): limit=2,702, allocated=168, free=105

**Comment by kevinmilner** [comment]
Hello, can you try running it with more memory and see if you still experience the issue? Run it like this in the console to allocate up to 4 GB of memory:

java -Xmx4G -jar HazardCurveGUI-1.5.2.jar

If you still see an issue, please paste console output into a reply here. Thanks!

**Comment by lstrahm** [comment]
Hi Kevin,

Thanks for the response.  I allocated 4GB and opened the software and got the same error message:




Thanks for your help with this.  I’m more than a bit lost when it comes to JAVA and LINUX.   I will try for 8GB for the heck of it, but wanted to get this to you before I lost it.
Larry Strahm

PS:

I also copied the following information from the Terminal that appeared upon opening the software:

lawrencestrahm@Lawrences-MacBook-Pro-2 Ground Motion % java -Xmx4G -jar HazardCurveGUI-1.5.2.jar
init: Epistemic List Control
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.opensha.commons.util.ExceptionUtils.asRuntimeException(ExceptionUtils.java:26)
	at org.opensha.sha.earthquake.ERF_Ref.instance(ERF_Ref.java:208)
	at org.opensha.sha.gui.beans.ERF_GuiBean.getERFInstance(ERF_GuiBean.java:176)
	at org.opensha.sha.gui.beans.ERF_GuiBean.parameterChange(ERF_GuiBean.java:532)
	at org.opensha.commons.param.AbstractParameter.firePropertyChange(AbstractParameter.java:386)
	at org.opensha.commons.param.AbstractParameter.setValue(AbstractParameter.java:210)
	at org.opensha.commons.param.editor.AbstractParameterEditor.setValue(AbstractParameterEditor.java:75)
	at org.opensha.commons.param.editor.impl.ConstrainedStringParameterEditor.itemStateChanged(ConstrainedStringParameterEditor.java:99)
	at javax.swing.JComboBox.fireItemStateChanged(JComboBox.java:1223)
	at javax.swing.JComboBox.selectedItemChanged(JComboBox.java:1271)
	at javax.swing.JComboBox.contentsChanged(JComboBox.java:1330)
	at javax.swing.AbstractListModel.fireContentsChanged(AbstractListModel.java:118)
	at javax.swing.DefaultComboBoxModel.setSelectedItem(DefaultComboBoxModel.java:93)
	at javax.swing.JComboBox.setSelectedItem(JComboBox.java:576)
	at javax.swing.JComboBox.setSelectedIndex(JComboBox.java:622)
	at javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(BasicComboPopup.java:868)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at com.apple.laf.AquaComboBoxPopup$1.processMouseEvent(AquaComboBoxPopup.java:157)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.opensha.sha.earthquake.ERF_Ref.instance(ERF_Ref.java:205)
	... 47 more
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at scratch.UCERF3.CompoundFaultSystemSolution.fromZipFile(CompoundFaultSystemSolution.java:320)
	at scratch.UCERF3.erf.UCERF3_CompoundSol_ERF.loadFetcher(UCERF3_CompoundSol_ERF.java:85)
	at scratch.UCERF3.erf.UCERF3_CompoundSol_ERF.<init>(UCERF3_CompoundSol_ERF.java:95)
	... 52 more

**Comment by lstrahm** [comment]
Hi Again Kevin,

I upped thee RAM to 8GB and got the same response.

Larry

**Comment by kevinmilner** [comment]
Hi Larry,

Thanks for sharing the stack trace. Did you see anything popups about a server issue as well? Our server was down yesterday, and that code should be trying to download a data file. Can you try again (with at least 4 GB of RAM) today and see if you get the same error?

Thanks,
Kevin

**Comment by lstrahm** [comment]
Hi Kevin,

I just tried and got the same response.  Then I tried using my old MacBook and it opens?  So, it doesn’t seem to be a problem on your end.  As I indicated, I am not really familiar with either Java or linux.  I compared settings for Java between my old MacBook Pro and my two new machines (MacBookPro and a PC).  The only difference I can find is the old machine is using update 271 of Java8 while the newer ones are running the update 281. I uninstalled 281 on my PC and replaced it with 271 and had the same problem.  The only other difference I noticed was that on the new machines OpenSHA is opened using JavaLauncher while on the old machine OpenSHA is opened using JarLauncher. I don’t know if that is meaningful or not.  If it is, I haven’t a clue how to change it.

I appreciate your trying to help[ me with this.  Let me know if you can think of anything else.  Since this doesn’t seem to have anything to do with OpenSHA, I may need to drop these machines off with a pro before I do anymore damage.

Thanks,
Larry

**Comment by kevinmilner** [comment]
OK, I think I know what's going on now. The app tries to download a data file, but if it crashes mid-download then it can get hung up next time you try to run it on the corrupted partial download. I thought that I had fixed this issue in version 1.5.2 of the apps, but it looks like that fix was only applied to the MeanUCERF3 ERF and not the single branch UCERF3 ERF. I have fixed this now and it will show up in our nightly builds as of tomorrow, and in the next release of the apps (which is not scheduled). In the meantime, you can manually delete the files in the following location and running it again:

On a mac: `~/.opensha/ucerf3_erf` (`~/` means your home directory, if you type the following in a terminal it should work: `rm ~/.opensha/ucerf3_erf/*`)
On a  PC: C:\Users\<your user name>\.opensha\ucerf3_erf

Let me know if that does the trick for you, and thanks for your patience!

edit: escaped the `~/` that GitHub was interpreting as strikethrough

**Comment by lstrahm** [comment]
Thanks.  I deleted the files, reran it and had a problem.  I thought if I did that now I wouldn’t need to wait until morning.

Dad

**Comment by lstrahm** [comment]
Hi Kevin,

I’ve deleted the files and will try again in the morning.

Thanks for your help!
Larry

**Comment by lstrahm** [comment]
Hi Kevin,

It works fine.  Thanks for your help!!!

Larry

**Comment by kevinmilner** [comment]
Great, I'm glad it worked for you! Closing this issue now.
