### ISSUE TITLE
Issue Running HazardCurveGUI-1.5.2: Server Down

### ISSUE THREAD

**Issue by dpteague** [opensha/opensha-apps#11]
Hi,

When I try to run disaggregation using the HazardCurveGUI-1.5.2 application, I get the following error indicating that the server is down. Do you know when the server will be running again and this issue will be resolved?

Thanks!

Application: HazardCurveLocal
Version: 1.5.2
Bulid Type: Production
Java Version: 1.8.0_241 (Oracle Corporation)
Operating System: Windows 10 (arch: amd64, version: 10.0)
JVM Memory (MB): limit=14,707, allocated=3,312, free=765

Exception:
```
java.lang.RuntimeException: Server is down , please try again later
	at org.opensha.sha.calc.disaggregation.DisaggregationCalculator.openServletConnection(DisaggregationCalculator.java:1119)
	at org.opensha.sha.calc.disaggregation.DisaggregationCalculator.getDisaggregationPlotUsingServlet(DisaggregationCalculator.java:854)
	at org.opensha.sha.gui.HazardCurveApplication.getDisaggregationPlot(HazardCurveApplication.java:2343)
	at org.opensha.sha.gui.HazardCurveApplication.showDisaggregationResults(HazardCurveApplication.java:1551)
	at org.opensha.sha.gui.HazardCurveApplication.computeHazardCurve(HazardCurveApplication.java:1459)
	at org.opensha.sha.gui.HazardCurveApplication.run(HazardCurveApplication.java:880)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by kevinmilner** [comment]
Hello, the server is indeed down due to a power issue in our server room. We're working on getting it back up, but it's been slower due to lack of IT people on campus during the pandemic. I think that someone is there today though, so hopefully it'll be back up soon and I'll close this ticket when it's back up so you know when.

**Comment by kevinmilner** [comment]
The server is now back up, please try again
