### ISSUE TITLE
Server Down

### ISSUE THREAD

**Issue by dpteague** [opensha/opensha-apps#13]
Hi - The server appears to have been down since yesterday morning. I get the following message when running disaggregation in HazardCurveGUI-1.5.2:

Steps to reproduce: (PLEASE FILL IN)

Other info: (PLEASE FILL IN)

Application: HazardCurveLocal
Version: 1.4.0
Bulid Type: Development
Java Version: 1.8.0_241 (Oracle Corporation)
Operating System: Windows 10 (arch: amd64, version: 10.0)

Exception:
{{{
java.lang.RuntimeException: Server is down , please try again later
	at org.opensha.sha.calc.disaggregation.DisaggregationCalculator.openServletConnection(DisaggregationCalculator.java:1113)
	at org.opensha.sha.calc.disaggregation.DisaggregationCalculator.getDisaggregationPlotUsingServlet(DisaggregationCalculator.java:848)
	at org.opensha.sha.gui.HazardCurveApplication.getDisaggregationPlot(HazardCurveApplication.java:2353)
	at org.opensha.sha.gui.HazardCurveApplication.showDisaggregationResults(HazardCurveApplication.java:1553)
	at org.opensha.sha.gui.HazardCurveApplication.computeHazardCurve(HazardCurveApplication.java:1461)
	at org.opensha.sha.gui.HazardCurveApplication.run(HazardCurveApplication.java:882)
	at java.lang.Thread.run(Unknown Source)
}}}

**Comment by kevinmilner** [comment]
I can't reproduce this issue, are you sure you're using a recent build? You mention that you're using the most recent version (1.5.2) but the bug report lists a development build of version 1.4.0, which would indeed no longer work. Can you re-download the latest release and try again? https://github.com/opensha/opensha-apps/releases

**Comment by dpteague** [comment]
The issue was the version. Thanks for pointing that out.
