### ISSUE TITLE
Bug in HazardSpectrumLocal

### ISSUE THREAD

**Issue by mdowninggeosyntec** [opensha/opensha-apps#15]
Steps to reproduce: (PLEASE FILL IN)

Other info: (PLEASE FILL IN)

Application: HazardSpectrumLocal
Version: 1.5.2
Bulid Type: Production
Java Version: 1.8.0_291 (Oracle Corporation)
Operating System: Windows 10 (arch: x86, version: 10.0)
JVM Memory (MB): limit=249, allocated=141, free=111

Exception:
```
java.lang.OutOfMemoryError: Java heap space
	at scratch.UCERF3.utils.MatrixIO.intListListFromInputStream(MatrixIO.java:630)
	at scratch.UCERF3.utils.FaultSystemIO.loadRupSetAsApplicable(FaultSystemIO.java:257)
	at scratch.UCERF3.utils.FaultSystemIO.loadSolAsApplicable(FaultSystemIO.java:527)
	at scratch.UCERF3.utils.FaultSystemIO.loadSolAsApplicable(FaultSystemIO.java:512)
	at scratch.UCERF3.utils.FaultSystemIO.loadSolAsApplicable(FaultSystemIO.java:497)
	at scratch.UCERF3.utils.FaultSystemIO.loadSol(FaultSystemIO.java:101)
	at scratch.UCERF3.erf.mean.MeanUCERF3.fetchSolution(MeanUCERF3.java:519)
	at scratch.UCERF3.erf.mean.MeanUCERF3.updateForecast(MeanUCERF3.java:291)
	at org.opensha.sha.gui.beans.ERF_GuiBean.getSelectedERF(ERF_GuiBean.java:384)
	at org.opensha.sha.gui.HazardSpectrumApplication.computeHazardCurve(HazardSpectrumApplication.java:218)
	at org.opensha.sha.gui.HazardCurveApplication.run(HazardCurveApplication.java:880)
	at java.lang.Thread.run(Unknown Source)
```

Metadata:

IMR Param List:
---------------
IMR = NGAWest2 2014 Averaged No Idriss; IMR Weights = ['Abrahamson, Silva & Kamai (2014)': 0.22, 'Boore, Stewart, Seyhan & Atkinson (2014)': 0.22, 'Campbell & Bozorgnia (2014)': 0.22, 'Chiou & Youngs (2014)': 0.22]; Std Dev Type = Total; Tectonic Region = Active Shallow Crust; Additional Epistemic Uncertainty = null; Component = RotD50; Gaussian Truncation = None

Site Param List: 
----------------
Longitude = -117.88224; Latitude = 33.65542; Vs30 = 290.0; Vs30 Type = Measured; Depth 2.5 km/sec = 1.83; Depth 1.0 km/sec = 467.0

IML/Prob Param List: 
---------------
Map Type = IML@Prob; Probability = 0.02

Forecast Param List: 
--------------------
Eqk Rup Forecast = USGS/CGS 1996 Adj. Cal. ERF; Fault Model = Frankel's; GR Fraction on B Faults = 0.5; Rupture Offset = 10.0; Background Seismicity = Exclude

TimeSpan Param List: 
--------------------
Duration = 50.0

Maximum Distance = 200.0; Pt Src Dist Corr = None

**Comment by mdowninggeosyntec** [comment]
I have installed extra RAM on my computer to run this application and yet it is still not running.

**Comment by kevinmilner** [comment]
Java requires that you tell it the maximum amount of memory that it is allowed to use before launching an application. If you don't do so, it chooses a memory limit automatically that is often too low. This line from the bug report indicates that you missed the step to allocate extra memory to java, and instead the application started with a limit of only 249 MB (not nearly enough):

> JVM Memory (MB): limit=249, allocated=141, free=111

Follow the instructions on our website to run the application with a higher memory limit and things should run more smoothly: https://opensha.org/Applications#launching-applications
