### ISSUE TITLE
WG02 Fortran Wrapped ERF List doesn't work

### ISSUE THREAD

**Issue by dinesher** [opensha/opensha-apps#8]
Steps to reproduce: (PLEASE FILL IN)

Other info: (PLEASE FILL IN)

Application: HazardCurveLocal
Version: 1.5.2
Bulid Type: Production
Java Version: 1.8.0_261 (Oracle Corporation)
Operating System: Windows 7 (arch: x86, version: 6.1)
JVM Memory (MB): limit=249, allocated=63, free=31

Exception:
```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at org.opensha.sha.earthquake.rupForecastImpl.WG02.WG02_FortranWrappedERF_EpistemicList.getDataForERF(WG02_FortranWrappedERF_EpistemicList.java:603)
	at org.opensha.sha.earthquake.rupForecastImpl.WG02.WG02_FortranWrappedERF_EpistemicList.getERF(WG02_FortranWrappedERF_EpistemicList.java:590)
	at org.opensha.sha.gui.HazardCurveApplication.handleForecastList(HazardCurveApplication.java:1624)
	at org.opensha.sha.gui.HazardCurveApplication.computeHazardCurve(HazardCurveApplication.java:1233)
	at org.opensha.sha.gui.HazardCurveApplication.run(HazardCurveApplication.java:880)
	at java.lang.Thread.run(Unknown Source)
```

Metadata:

Cacluation Type = Probabilistic

IMR Param List:
---------------
IMR = Campbell and Bozorgnia (2003); Gaussian Truncation = None; Tectonic Region = Active Shallow Crust; Component = Average Horizontal; Std Dev Type = Total (Mag Dependent)

Site Param List: 
----------------
Longitude = -118.25; Latitude = 34.05; Campbell-2003 Site Type = Very-Firm-Soil

IMT Param List: 
---------------
IMT = PGA

Forecast Param List: 
--------------------
Eqk Rup Forecast = WG02 Fortran Wrapped ERF List; Rupture Offset = 10.0; Fault Discretization = 2.0; Delta Mag = 0.1; Back

**Comment by kevinmilner** [comment]
Thank you for the bug report. I'm not quite sure why you closed it as this does seem to indeed be a bug, so I'm reopening and working on fixing it now.

**Comment by kevinmilner** [comment]
I have now fixed this issue. It was a server-side issue, so we don't need to re-release the apps, and existing builds should work now.

See here for more info: https://github.com/opensha/opensha-core/pull/13
